#encoding \uc5b8\uc5b4\uc14b
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

#jsp
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

#\ud3ec\ud2b8 \ubcc0\uacbd
server.port = 8091

#DB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/sweeper
spring.datasource.username=postgres
spring.datasource.password=1234

#mybatis.type-aliases-package=com.demo.demoApi.model ??
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

#error log
logging.level.root=INFO
logging.level.com.sweeper.car=DEBUG
